### ISSUE TITLE
Should we consider a new JBake template

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unitsofmeasurement-jbake#22]
@manikmagar created a nice fancy HTML5 JBake template https://github.com/manikmagar/jbake-future-imperfect-template used e.g. by https://unittesters.com/.

Should we consider using something here between now and JSR 385 Final?

**Comment by manikmagar** [comment]
Thanks for the consideration. It should work with latest JBake 2.6.0 too.

**Comment by keilw** [comment]
One problem I see with this template is the lack of menu links. @manikmagar, does that exist or could it be configured somehow?

**Comment by manikmagar** [comment]
Sorry for so late reply @keilw. Unfortunately nested links are not supported in there. I will see if I can enable that.

**Comment by keilw** [comment]
Thanks @manikmagar it is not the most urgent task, but if the template was improved, please let us know, then we could try it out.

**Comment by keilw** [comment]
I think after the breadcrumb issue is resolved, we can close this for now and may revisit if the template might improve.
