### ISSUE TITLE
How to add an event on the calendar?

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/unitsofmeasurement-jbake#30]
It looks like [this](https://unitsofmeasurement.github.io/pages/calendar.html) is a private agenda injected as an `iframe` on our code. Could we somehow enable more people to edit it? 

For example, I already see some potential for a few additional events (e.g. World Metrology Day, Adopt-a-JSR Day for Utrecht JUG, etc.).

**Comment by keilw** [comment]
You need a Google Calendar, but I'm not sure, if this can be shared like Google Docs with others to edit. The calendar is for UoM only, not a private calendar.

**Comment by keilw** [comment]
It seems the only way with Google Calendar is to invite other guests who are able to edit an event. Just did it for the adopt event.
