### ISSUE TITLE
Allow multiple authors

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/unitsofmeasurement-jbake#33]
We currently use only one author for our posts (`meta.author` tag at `jbake.properties` file).

Changing the author at the above place will create a ton of changes in all the generated htmls, like below:

![Screenshot 2019-07-22 at 21 53 30](https://user-images.githubusercontent.com/5684688/61660907-3c35ad00-accb-11e9-8a3c-ad848e6cfb75.png)

Undoubtedly, we should avoid this and find a smart way to deal with multiple authors, instead.

**Comment by keilw** [comment]
Does JBake support this already?

**Comment by keilw** [comment]
As it is unclear, if JBake will ever support this, will close it. The sub-sites under the respective `repo/docs` folder contain static HTML content where the author can be manually changed, so a different author can be used for API, RI etc.
